export const Paths = {
  posts: '/[userName]',
  userCategories: '/[userName]/category/[categoryName]',
  post: '/[userName]/posts/[postId]',
  favoriteUsers: '/[userName]/posts/[postId]/favorites',
  newPost: '/[userName]/posts/new',
  mylist: '/[userName]/mylist',
  favorites: '/[userName]/favorites',
  following: '/[userName]/following',
  followers: '/[userName]/followers',
  searchUsers: '/search',
  top: '/',
  home: '/home',
  login: '/login',
  settings: '/settings',
  registration: '/settings/registration',
} as const;
