export const Paths = {
  posts: '/users/[userName]',
  userCategories: '/users/[userName]/category/[categoryName]',
  post: '/users/[userName]/posts/[postId]',
  favoriteUsers: '/users/[userName]/posts/[postId]/favorites',
  newPost: '/users/[userName]/posts/new',
  favorites: '/users/[userName]/favorites',
  following: '/users/[userName]/following',
  followers: '/users/[userName]/followers',
  top: '/',
  home: '/home',
  login: '/login',
  terms: '/terms',
  privacy: '/privacy',
  settings: '/settings',
  withdraw: '/settings/withdraw',
  categorySettings: '/settings/category',
  registration: '/settings/registration',
} as const;
