import { Box, Button, Divider, useColorMode } from '@chakra-ui/react';
import { NextAppPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { TopPage } from '@/components/pages/top/Top.page';
import { supabaseClient } from '@/lib/supabase/client';
import { useAuthDispatch } from '@/services/auth/AuthProvider';
import { Link } from '@/utils/route/Link';
import { Paths } from '@/utils/route/paths';

export const Page: NextAppPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();
  const { signIn, signOut } = useAuthDispatch();

  const refreshSession = async () => {
    const res = await supabaseClient.auth.refreshSession();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div></div>
        <div>
          <button onClick={refreshSession}>reflesh</button>
        </div>
        <div>
          <Link
            path={Paths.settings}
            chakraLinkProps={{ colorScheme: 'primary' }}
          >
            Settings Page
          </Link>
        </div>
        <div>
          <Link
            path={Paths.registration}
            chakraLinkProps={{ colorScheme: 'primary' }}
          >
            RegistrationPage{' '}
          </Link>
        </div>
        <div>
          <Link path={Paths.posts} params={{ userName: 'MiraiPuzzle' }}>
            MiraiPuzzle
          </Link>
        </div>

        <div>
          <Link path={Paths.home}>Home Page</Link>
        </div>
        <Box p="4">
          <Button onClick={toggleColorMode}>
            Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
          </Button>
        </Box>

        <Box bgColor="primary.500" h="50px" opacity="0.08">
          aaaa
        </Box>
        <Box bgColor="#121212" h="50px" mt="-4">
          dfs
        </Box>
        <Button onClick={signIn}>Twitterでログインテスト</Button>
      </main>
      <Divider />
      <TopPage />
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Page;
